version: '3'
services:
  bd:
    image: postgres
    container_name: database
    restart: always
    volumes:
      - ./dump/:/data/db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: super_cool_blog_db
      POSTGRES_DB: blog
